### ISSUE TITLE
i can't build

### ISSUE THREAD

**Issue by QuintenQVD0** [Foxxite/MultiCharacter#6]
I cant build it because there are dependency provided and i don't have those. Can you edit the pom.xml to download them from the website and don't try 0.0.0.0 or explain to me how to download these or give an example to edit the pom.xml myself?

**Comment by Foxxite** [comment]
Make sure you have the Lombok plugin installed for your IDE, all other dependencies should be downloaded by Maven.

[https://projectlombok.org/](
https://projectlombok.org/)
